---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - box: Megabyte/Fedora-Desktop
    cpus: 2
    memory: 4096
    name: Fedora-34
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
provisioner:
  inventory:
    group_vars:
      all:
        virtualbox_molecule_test: true
  name: ansible
  options:
    vvv: true
  playbooks:
    converge: converge.yml
scenario:
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  create_sequence:
    - dependency
    - create
    - prepare
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
