---
description: Run the play on the localhost
driver:
  name: delegated
  options:
    ansible_connection_options:
      ansible_connection: local
    managed: false
platforms:
  - name: instance
provisioner:
  connection_options:
    ansible_password: ${TEST_PASSWORD:-ansible}
    ansible_ssh_user: ${TEST_USER:-ansible}
    ansible_user: ${TEST_USER:-ansible}
scenario:
  check_sequence:
    - dependency
    - cleanup
    - prepare
    - converge
    - check
  converge_sequence:
    - dependency
    - prepare
    - converge
  create_sequence:
    - dependency
    - prepare
  destroy_sequence:
    - dependency
    - cleanup
  test_sequence:
    - dependency
    - lint
    - cleanup
    - syntax
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
