---
version: '3'

tasks:
  check:package:
    deps:
      - :install:software:jq
    vars:
      BLUEPRINT_REQUIRED_FIELDS: description group name overview slug subgroup title
    cmds:
      - |
        ALREADY_PRESENT=true
        for ITEM in {{.BLUEPRINT_REQUIRED_FIELDS}}; do
          VALUE="$(jq --arg item "$ITEM" -r '.blueprint[$item]' package.json)"
          if [ "$VALUE" == 'null' ]; then
            ALREADY_PRESENT=false
            break
          fi
        done
        if [ "$ALREADY_PRESENT" == 'true' ]; then
          GITHUB="$(jq -r '.blueprint.repository.github' package.json)"
          GITLAB="$(jq -r '.blueprint.repository.gitlab' package.json)"
          if [ "$GITHUB" == 'null' ] || [ "$GITLAB" == 'null' ]; then
            ALREADY_PRESENT=false
          fi
        fi
        if [ ! -f 'package.json' ] || [ "$ALREADY_PRESENT" == 'false' ]; then
          node .config/scripts/prompts/package.js
          task boilerplate:update:taskfile
        fi

  update:taskfile:
    deps:
      - :install:software:yq
    cmds:
      - |
        GROUP="$(jq -r '.blueprint.group' package.json)"
        SUBGROUP="$(jq -r '.blueprint.subgroup' package.json)"
        TASK_GROUP="$(yq eval '.vars.REPOSITORY_TYPE' Taskfile.yml)"
        TASK_SUBGROUP="$(yq eval '.vars.REPOSITORY_SUBTYPE' Taskfile.yml)"
        if [ "$GROUP" != "$TASK_GROUP" ]; then
          yq e -i '.vars.REPOSITORY_TYPE = strenv(GROUP)' Taskfile.yml
        fi
        if [ "$SUBGROUP" != "$TASK_SUBGROUP" ]; then
          yq e -i '.vars.REPOSITORY_SUBTYPE = strenv(GROUP)' Taskfile.yml
        fi
