---
galaxy:webhook:
  image:
    name: megabytelabs/yamllint:slim
    entrypoint: ['']
  rules:
    - if: $DO_CI == 'false'
      when: never
  script:
    - set -eo pipefail
    - yamllint -c .config/yamllint.yml -s .
  stage: publish
  variables:
    GIT_DEPTH: 1
