---
description: Test on Google Cloud Platform (Linux)
driver:
  auth_kind: serviceaccount
  external_access: false
  instance_os_type: linux
  name: gce
  project_id: megabyte-labs
  region: us-east4
  scopes:
    - 'https://www.googleapis.com/auth/compute'
  service_account_file: ~/gcp.json
groups:
  CentOS: Test on all CentOS images
  CentOS-7: Test on CentOS 7
  CentOS-8: Test on CentOS 8
  CentOS-Stream-8: Test on CentOS Stream 8
  Debian: Test on all Debian images
  Debian-10: Test on Debian 10
  Debian-11: Test on Debian 11
  Debian-9: Test on Debian 9
  Debian-Flavor: Test on all Debian-flavored images
  Fedora: Test on all Fedora images
  Fedora-35: Test on Fedora 35 (Core OS)
  Linux: Test on all linux platforms
  RedHat-Flavor: Test on all RedHat-flavored images
  Ubuntu: Test on all Ubuntu images
  Ubuntu-18.04: Test on Ubuntu 18.04
  Ubuntu-20.04: Test on Ubuntu 20.04
  Ubuntu-21.04: Test on Ubuntu 21.04
  Ubuntu-21.10: Test on Ubuntu 21.10
platforms:
  - groups:
      - CentOS
      - CentOS-7
      - Linux
      - RedHat-Flavor
    image: projects/centos-cloud/global/images/family/centos-7
    machine_type: e2-small
    name: centos-7
    zone: us-east4-a
  - groups:
      - CentOS
      - CentOS-8
      - Linux
      - RedHat-Flavor
    image: projects/centos-cloud/global/images/family/centos-8
    machine_type: e2-small
    name: centos-8
    zone: us-east4-a
  - groups:
      - CentOS
      - CentOS-Stream-8
      - Linux
      - RedHat-Flavor
    image: projects/centos-cloud/global/images/family/centos-stream-8
    machine_type: e2-small
    name: centos-stream-8
    zone: us-east4-a
  - groups:
      - Debian
      - Debian-9
      - Debian-Flavor
      - Linux
    image: projects/debian-cloud/global/images/family/debian-9
    machine_type: e2-small
    name: debian-9-stretch
    zone: us-east4-a
  - groups:
      - Debian
      - Debian-10
      - Debian-Flavor
      - Linux
    image: projects/debian-cloud/global/images/family/debian-10
    machine_type: e2-small
    name: debian-10-buster
    zone: us-east4-a
  - groups:
      - Debian
      - Debian-11
      - Debian-Flavor
      - Linux
    image: projects/debian-cloud/global/images/family/debian-11
    machine_type: e2-small
    name: debian-11-bullseye
    zone: us-east4-a
  - groups:
      - Fedora
      - Fedora-35
      - Linux
      - RedHat-Flavor
    image: projects/fedora-coreos-cloud/global/images/family/fedora-coreos-stable
    machine_type: e2-small
    name: fedora-coreos-35
    zone: us-east4-a
  - groups:
      - Debian-Flavor
      - Linux
      - Ubuntu
      - Ubuntu-18.04
    image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts
    machine_type: e2-small
    name: ubuntu-1804-bionic-beaver
    zone: us-east4-a
  - groups:
      - Debian-Flavor
      - Linux
      - Ubuntu
      - Ubuntu-20.04
    image: projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts
    machine_type: e2-small
    name: ubuntu-2004-focal-fossa
    zone: us-east4-a
  - groups:
      - Debian-Flavor
      - Linux
      - Ubuntu
      - Ubuntu-21.04
    image: projects/ubuntu-os-cloud/global/images/family/ubuntu-2104
    machine_type: e2-small
    name: ubuntu-2104-hirsute-hippo
    zone: us-east4-a
  - groups:
      - Debian-Flavor
      - Linux
      - Ubuntu
      - Ubuntu-21.10
    image: projects/ubuntu-os-cloud/global/images/family/ubuntu-2110
    machine_type: e2-small
    name: ubuntu-2110-impish-indri
    zone: us-east4-a
