---
lint:flake8:
  stage: lint
  image:
    name: megabytelabs/flake8:slim
    entrypoint: ['']
  rules:
    - if: $DO_CI == 'false'
      when: never
    - if: $CI_COMMIT_BRANCH == 'synchronize'
      when: never
    - exists:
        - '**/*.py'
  needs: []
  variables:
    GIT_DEPTH: 1
  script:
    - set -eo pipefail
    - flake8 --config .config/flake8.toml .
