---
lint:flake8:
  stage: lint
  image:
    name: megabytelabs/flake8:slim
    entrypoint: ['']
  rules:
    - exists:
        - '**/*.py'
  variables:
    GIT_DEPTH: 1
  script:
    - set -eo pipefail
    - flake8 .
