---
dist: focal
os: linux
language: python
python:
  - '3.8'
git:
  submodules: false

jobs:
  include:
    - name: Ubuntu 20.04 (ARM64)
      os: linux
      dist: focal
      arch: arm64
      language: python
      python:
        - 3.8
      script:
        - bash start.sh
        - task ansible:test:local
