---
version: '3'

output: prefixed

vars:
  GALAXY_ROLE_NAME:
    sh: if [ -f meta/main.yml ]; then yq e '.galaxy_info.role_name' meta/main.yml; else jq -r '.name' package.json | sed 's/.*\///'; fi
  GALAXY_NAMESPACE:
    sh: if [ -f meta/main.yml ]; then yq e '.galaxy_info.namespace' meta/main.yml; else jq -r '.name' package.json | sed 's/\/.*//' | sed 's/@//'; fi
  REPOSITORY_SUBTYPE: role
  REPOSITORY_TYPE: ansible

includes:
  ansible: ./.common/taskfiles-role/Taskfile-ansible.yml
  common: ./.common/taskfiles-role/Taskfile-common.yml
  fix: ./.common/taskfiles-role/Taskfile-fix.yml
  git: ./.common/taskfiles-playbook/Taskfile-git.yml
  image: ./.common/taskfiles-role/Taskfile-image.yml
  lint: ./.common/taskfiles-role/Taskfile-lint.yml
  npm: ./.common/taskfiles-role/Taskfile-npm.yml
  python: ./.common/taskfiles-role/Taskfile-python.yml
  security: ./.common/taskfiles-role/Taskfile-security.yml
  software: ./.common/taskfiles-role/Taskfile-{{OS}}.yml
  test: ./.common/taskfiles-role/Taskfile-test.yml
  vscode: ./.common/taskfiles-role/Taskfile-vscode.yml

tasks:
  start:
    desc: Set up the project and refresh it with the latest changes
    summary: |
      # Set up the project

      This task will scaffold the project with the latest upstream changes
      and ensure your development environment has all the dependencies installed.

      **Example usage:**
      `task start`
    cmds:
      - task: common:update
