---
version: "3"

output: prefixed

vars:
  GALAXY_ROLE_NAME:
    sh: if [ -f meta/main.yml ]; then yq e '.galaxy_info.role_name' meta/main.yml; else jq -r '.name' package.json | sed 's/.*\///'; fi
  GALAXY_NAMESPACE:
    sh: if [ -f meta/main.yml ]; then yq e '.galaxy_info.namespace' meta/main.yml; else jq -r '.name' package.json | sed 's/\/.*//' | sed 's/@//'; fi
  REPOSITORY_SUBTYPE: role
  REPOSITORY_TYPE: ansible

includes:
  common: ./.common/taskfiles-role/Taskfile-common.yml
  ansible: ./.common/taskfiles-role/Taskfile-ansible.yml
  fix: ./.common/taskfiles-role/Taskfile-fix.yml
  lint: ./.common/taskfiles-role/Taskfile-lint.yml
  software: ./.common/taskfiles-role/Taskfile-{{OS}}.yml
