---
publish:pypi:binary:
  stage: publish
  image:
    name: megabytelabs/yamllint:slim
    entrypoint: ['']
  variables:
    GIT_DEPTH: 1
  script:
    - set -eo pipefail
    - yamllint -c .config/yamllint.yml -s .
