---
version: '3'

vars:
  MAIN_TASKS_PATH: tasks/main.yml
  META_PATH: meta/main.yml
  MOLECULE_RESULTS_PATH: molecule/.results
  REQUIREMENTS_PATH: requirements.yml
  VARIABLES_PATH: .variables.json

tasks:
  ansibler:
    deps:
      - :install:python:requirements
    cmds:
      - task: compatibility-chart
      - task: tasks:{{.REPOSITORY_SUBTYPE}}
    preconditions:
      - sh: 'type ansibler &> /dev/null'
        msg: '`ansibler` is not installed globally.'

  compatibility-chart:
    deps:
      - :install:software:jq
    env:
      TMP:
        sh: mktemp
    cmds:
      - task: compatibility-chart:generate
      - jq -s -S '.[0] + .[1]' '{{.VARIABLES_PATH}}' .cache/compatibility-chart.json > "$TMP"
      - mv "$TMP" '{{.VARIABLES_PATH}}'

  compatibility-chart:generate:
    deps:
      - :install:python:requirements
    env:
      TMP:
        sh: mktemp
    cmds:
      - mkdir -p .cache
      - ansibler --generate-compatibility-chart --molecule-results-dir '{{.MOLECULE_RESULTS_PATH}}' --json-file .cache/compatibility-chart.json
    sources:
      - '{{.MOLECULE_RESULTS_PATH}}/*'
    generates:
      - .cache/compatibility-chart.json

  populate-platforms:
    deps:
      - :install:software:jq
    env:
      TMP:
        sh: mktemp
    cmds:
      - task: populate-platforms:generate
      - jq -s -S '.[0] + .[1]' '{{.VARIABLES_PATH}}' .cache/platforms.json > "$TMP"
      - mv "$TMP" '{{.VARIABLES_PATH}}'

  populate-platforms:generate:
    deps:
      - :install:python:requirements
      - :install:npm:prettier
    cmds:
      - mkdir -p .cache
      - ansibler --populate-platforms --json-file .cache/platforms.json
      - >
        {{.NPX_HANDLE}}prettier --write '{{.META_PATH}}'
    sources:
      - '{{.MAIN_TASKS_PATH}}'
      - '{{.MOLECULE_RESULTS_PATH}}/*'
    generates:
      - .cache/platforms.json

  role-dependencies:
    deps:
      - :install:software:jq
    env:
      TMP:
        sh: mktemp
    cmds:
      - task: role-dependencies:generate
      - jq -s -S '.[0] + .[1]' '{{.VARIABLES_PATH}}' .cache/role-dependencies.json > "$TMP"
      - mv "$TMP" '{{.VARIABLES_PATH}}'

  role-dependencies:generate:
    deps:
      - :install:python:requirements
    cmds:
      - mkdir -p .cache
      - cmd: ansibler --role-dependencies --json-file .cache/role-dependencies.json
        ignore_error: true
    sources:
      - '{{.REQUIREMENTS_PATH}}'
    generates:
      - .cache/role-dependencies.json

  tasks:playbook:
    deps:
      - :ansible:collection-dependencies
      - role-dependencies

  tasks:role:
    deps:
      - :ansible:collection-dependencies
      - populate-platforms
      - role-dependencies
