---
version: '3'

vars:
  MAIN_TASKS_PATH: tasks/main.yml
  META_PATH: meta/main.yml
  MOLECULE_RESULTS_PATH: molecule/.results
  REQUIREMENTS_PATH: requirements.yml
  VARIABLES_PATH: .variables.json

tasks:
  ansibler:
    deps:
      - :install:python:requirements
    cmds:
      - task: compatibility-chart
      - task: tasks:{{.REPOSITORY_SUBTYPE}}
    preconditions:
      - sh: 'type ansibler &> /dev/null'
        msg: '`ansibler` is not installed globally.'

  compatibility-chart:
    deps:
      - :install:software:jq
    cmds:
      - mkdir -p .cache
      - if [ ! -f .cache/compatibility-chart.json ]; then echo "{}" > .cache/compatibility-chart.json; fi
      - task: compatibility-chart:generate
      - |
        TMP="$(mktemp)"
        jq -s -S '.[0] + .[1]' '{{.VARIABLES_PATH}}' .cache/compatibility-chart.json > "$TMP"
        mv "$TMP" '{{.VARIABLES_PATH}}'
      - task: populate-platforms

  compatibility-chart:generate:
    deps:
      - :install:python:requirements
    cmds:
      - ansibler --generate-compatibility-chart --molecule-results-dir '{{.MOLECULE_RESULTS_PATH}}' --json-file .cache/compatibility-chart.json
    sources:
      - '{{.MOLECULE_RESULTS_PATH}}/*'
    generates:
      - .cache/compatibility-chart.json

  populate-platforms:
    deps:
      - :install:python:requirements
    cmds:
      - ansibler --populate-platforms --json-file .cache/compatibility-chart.json
    sources:
      - .cache/compatibility-chart.json
      - meta/main.yml

  role-dependencies:
    deps:
      - :install:software:jq
    cmds:
      - mkdir -p .cache
      - if [ ! -f .cache/role-dependencies.json ]; then echo "{}" > .cache/role-dependencies.json; fi
      - task: role-dependencies:generate
      - if [ -f role-dependencies.json ]; then mv role-dependencies.json .cache/role-dependencies.json; fi
      - |
        TMP="$(mktemp)"
        jq -s -S '.[0] + .[1]' '{{.VARIABLES_PATH}}' .cache/role-dependencies.json > "$TMP"
        mv "$TMP" '{{.VARIABLES_PATH}}'

  role-dependencies:generate:
    deps:
      - :install:python:requirements
    cmds:
      - cmd: ansibler --role-dependencies --json-file .cache/role-dependencies.json
        ignore_error: true
    sources:
      - '{{.REQUIREMENTS_PATH}}'
    generates:
      - .cache/role-dependencies.json

  tasks:playbook:
    deps:
      - :ansible:collection-dependencies
      - role-dependencies

  tasks:role:
    deps:
      - :ansible:collection-dependencies
      - populate-platforms
      - role-dependencies
