---
version: '3'

vars:
  MAIN_TASKS_PATH: tasks/main.yml
  META_PATH: meta/main.yml
  MOLECULE_RESULTS_PATH: molecule/.results
  REQUIREMENTS_PATH: requirements.yml
  VARIABLES_PATH: .variables.json

tasks:
  ansibler:
    deps:
      - :install:python:requirements
    cmds:
      - task: compatibility-chart
      - task: tasks:{{.REPOSITORY_SUBTYPE}}

  compatibility-chart:
    deps:
      - :install:software:jq
    cmds:
      - mkdir -p .cache
      - if [ ! -f .cache/compatibility-chart.json ]; then echo "{}" > .cache/compatibility-chart.json; fi
      - task: compatibility-chart:generate
      - |
        TMP="$(mktemp)"
        jq -s -S '.[0] + .[1]' '{{.VARIABLES_PATH}}' .cache/compatibility-chart.json > "$TMP"
        mv "$TMP" '{{.VARIABLES_PATH}}'
      - task: populate-platforms

  compatibility-chart:generate:
    deps:
      - :install:python:requirements
    cmds:
      - >
        .config/log info 'Generating compatibility chart'

        {{.PYTHON_HANDLE}}ansibler --generate-compatibility-chart --molecule-results-dir '{{.MOLECULE_RESULTS_PATH}}'
        --json-file .cache/compatibility-chart.json

        .config/log success 'Successfully generated compatibility chart'
    sources:
      - '{{.MOLECULE_RESULTS_PATH}}/*'
    generates:
      - .cache/compatibility-chart.json

  populate-platforms:
    deps:
      - :install:python:requirements
    cmds:
      - |
        .config/log info 'Populating the supported platforms listed in meta/main.yml based on the compatibility chart data'

        {{.PYTHON_HANDLE}}ansibler --populate-platforms --json-file .cache/compatibility-chart.json

        .config/log success 'Successfully populated platforms in meta/main.yml based on the compatibility chart data'
    sources:
      - .cache/compatibility-chart.json
      - meta/main.yml

  role-dependencies:
    deps:
      - :install:software:jq
    cmds:
      - mkdir -p .cache
      - if [ ! -f .cache/role-dependencies.json ]; then echo "{}" > .cache/role-dependencies.json; fi
      - task: role-dependencies:generate
      - if [ -f role-dependencies.json ]; then mv role-dependencies.json .cache/role-dependencies.json; fi
      - |
        TMP="$(mktemp)"
        jq -s -S '.[0] + .[1]' '{{.VARIABLES_PATH}}' .cache/role-dependencies.json > "$TMP"
        mv "$TMP" '{{.VARIABLES_PATH}}'

  role-dependencies:generate:
    deps:
      - :install:python:requirements
    cmds:
      - cmd: |
          .config/log info 'Gathering information about role dependencies'
          {{.PYTHON_HANDLE}}ansibler --role-dependencies --json-file .cache/role-dependencies.json
          .config/log success 'Acquired role dependency information'
        ignore_error: true
    sources:
      - '{{.REQUIREMENTS_PATH}}'
    generates:
      - .cache/role-dependencies.json

  tasks:playbook:
    deps:
      - :ansible:collection-dependencies
      - role-dependencies

  tasks:role:
    deps:
      - :ansible:collection-dependencies
      - populate-platforms
      - role-dependencies
