---
python:artifacts:
  image:
    name: megabytelabs/yamllint:slim
    entrypoint: ['']
  script:
    - set -eo pipefail
    - yamllint -c .config/yamllint.yml -s .
  stage: publish
  variables:
    GIT_DEPTH: 1
