---
# @action Ensures Android Studio is installed
# Installs Android Studio on macOS using Homebrew
- name: "Ensure {{ app_name }} is installed"
  become: false
  community.general.homebrew_cask:
    name: android-studio
    state: "{{ app_state | default('present') }}"
    accept_external_apps: "{{ allow_external_apps | default(false) }}"
