---
# @action Ensures Android Studio is installed
# Installs Android Studio on Linux using snap
- name: "Ensure {{ app_name }} is installed"
  community.general.snap:
    name: android-studio
    classic: true
    state: "{{ app_state | default('present') }}"
