---
pages:
  stage: publish
  allow_failure: true
  rules:
    - if: $DO_CI == 'false'
      when: never
  variables:
    GIT_DEPTH: 1
  script:
    - set -eo pipefail
    - mv build/docs/ public/
  artifacts:
    paths:
      - public
