---
pages:
  stage: publish
  allow_failure: true
  only:
    - master
  variables:
    GIT_DEPTH: 1
  script:
    - set -eo pipefail
    - mv build/docs/ public/
  artifacts:
    paths:
      - public
