---
lint:markdown:
  image: pipelinecomponents/markdownlint
  rules:
    - if: $DO_CI == 'false'
      when: never
    - exists:
        - '**/*.md'
  script:
    - set -eo pipefail
    - mdl .
  stage: lint
  variables:
    GIT_DEPTH: 1
