---
lint:markdown:
  stage: lint
  image: pipelinecomponents/markdownlint
  rules:
    - if: $DO_CI == 'false'
      when: never
    - if: $CI_COMMIT_BRANCH == 'synchronize'
      when: never
    - exists:
        - '**/*.md'
  needs: []
  variables:
    GIT_DEPTH: 1
  script:
    - set -eo pipefail
    - mdl .
