---
lint:standard:
  before_script:
    - git config pull.ff only
    - git checkout "$CI_COMMIT_REF_NAME"
    - git pull origin "$CI_COMMIT_REF_NAME"
  image:
    name: megabytelabs/standard:slim
    entrypoint: ['']
  rules:
    - exists:
        - '**/*.js'
  script:
    - set -eo pipefail
    - standard
  stage: lint
  variables:
    GIT_DEPTH: 1
