---
lint:tflint:
  image:
    name: megabytelabs/tflint:slim
    entrypoint: ['']
  rules:
    - if: $DO_CI == 'false'
      when: never
  script:
    - set -eo pipefail
    - tflint
  stage: lint
  variables:
    GIT_DEPTH: 1
