---
fix:eslint:
  image:
    name: megabytelabs/yamllint:slim
    entrypoint: ['']
  rules:
    - if: $DO_CI == 'false'
      when: never
    - exists:
        - '**/*.{js,jsx,json,json.handlebars,toml,ts,tsx,yml}'
  script:
    - set -eo pipefail
    - yamllint -c .config/yamllint.yml -s .
  stage: fix
  variables:
    GIT_DEPTH: 1
