---
fix:packer:
  stage: fix
  image:
    name: megabytelabs/packer:slim
    entrypoint: ['']
  rules:
    - if: $DO_CI == 'false'
      when: never
    - if: $CI_COMMIT_TITLE =~ /^automation\(.*/
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      exists:
        - '*template.json'
  variables:
    GIT_DEPTH: 1
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - git config pull.ff only
    - git remote set-url origin "https://root:$GROUP_ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
    - git config user.email "$GITLAB_CI_EMAIL"
    - git config user.name "$GITLAB_CI_NAME"
    - git pull
  script:
    - set -eo pipefail
    - echo "Not in use due to conflicts with Prettier autoformatting"
