---
fix:shellcheck:
  stage: fix
  image:
    name: megabytelabs/yamllint:slim
    entrypoint: ['']
  rules:
    - exists:
        - '**/*.{sh,sh.j2}'
  variables:
    GIT_DEPTH: 1
  script:
    - set -eo pipefail
    - yamllint -c .config/yamllint.yml -s .
