---
version: '3'

tasks:
  install-doctor:
    cmds:
      - |
        if ! type {{.SOFTWARE}} &> /dev/null; then
          true info 'Using https://install.doctor to install `{{.SOFTWARE}}`'
          curl -sS https://install.doctor/{{.SOFTWARE}} | bash
        fi
    status:
      - type {{.SOFTWARE}} &> /dev/null || [[ "${container:=}" == "docker" ]]

  modules:global:
    deps:
      - :install:npm:{{.NPM_PROGRAM}}
    run: once
    cmds:
      - task: :install:npm:commitizen
      - task: :install:npm:commitlint
      - task: :install:npm:cspell
      - task: :install:npm:eslint
      - task: :install:npm:hbs
      - task: :install:npm:husky
      - task: :install:npm:lint-staged
      - task: :install:npm:prettier
      - task: :install:npm:readme
      - task: :install:npm:remark
      - task: :install:npm:shellcheck
      - task: :install:npm:standard-version
    status:
      - '[[ "${container:=}" == "docker" ]]'

  modules:local:
    deps:
      - :install:npm:{{.NPM_PROGRAM}}
    vars:
      NPM_DEPS:
        sh: jq -r -S '.dependencies' package.json
      NPM_DEVDEPS:
        sh: jq -r -S '.devDependencies' package.json
    run: when_changed
    cmds:
      - '{{.NPM_PROGRAM}} install'
      - cmd: '{{.NPM_PROGRAM}} audit fix || true'
        ignore_error: true
    sources:
      - package.json
