---
# INFO: This file is the entrypoint for the role's logic
- name: Include variables based on the operating system
  include_vars: '{{ ansible_os_family }}.yml'

- name: Include tasks based on the operating system
  become: true
  block:
    - include_tasks: 'install-{{ ansible_os_family }}.yml'
