---
version: '3'

tasks:
  semantic-release:
    deps:
      - :install:modules:local
      - :install:npm:semantic-release
      - :install:software:poetry
    log:
      error: Error while running `semantic-release`
      start: Releasing with `semantic-release`..
      success: Finished running `semantic-release`
    cmds:
      - semantic-release
