---
description: Test on (mostly) headless VirtualBox instances
driver:
  name: vagrant
  provider:
    name: virtualbox
groups:
  ArchLinux: Test on ArchLinux
  CentOS: Test on all CentOS images
  CentOS-7: Test on CentOS 7
  CentOS-8: Test on CentOS 8
  CentOS-Stream-8: Test on CentOS Stream 8
  Debian: Test on all Debian images
  Debian-10: Test on Debian 10
  Debian-11: Test on Debian 11
  Debian-9: Test on Debian 9
  Debian-Flavor: Test on all Debian-flavored images
  Fedora: Test on all Fedora images
  Fedora-33: Test on Fedora 33
  Fedora-34: Test on Fedora 34
  Fedora-35: Test on Fedora 35
  Linux: Test on all linux platforms
  RedHat-Flavor: Test on all RedHat-flavored images
  Ubuntu: Test on all Ubuntu images
  Ubuntu-18.04: Test on Ubuntu 18.04
  Ubuntu-20.04: Test on Ubuntu 20.04
  Ubuntu-21.04: Test on Ubuntu 21.04
  Ubuntu-21.10: Test on Ubuntu 21.10
  Windows: Test on Windows 10 desktop
platforms:
  - box: archlinux/archlinux
    cpus: 1
    groups:
      - ArchLinux
      - Linux
    memory: 512
    name: ArchLinux-Latest
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: bento/centos-7
    cpus: 1
    groups:
      - CentOS
      - CentOS-7
      - Linux
      - RedHat-Flavor
    memory: 512
    name: CentOS-7
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: bento/centos-8
    cpus: 1
    groups:
      - CentOS
      - CentOS-8
      - Linux
      - RedHat-Flavor
    memory: 512
    name: CentOS-8
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: bento/centos-stream-8
    cpus: 1
    groups:
      - CentOS
      - CentOS-Stream-8
      - Linux
      - RedHat-Flavor
    memory: 512
    name: CentOS-Stream-8
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: bento/debian-9
    cpus: 1
    groups:
      - Debian
      - Debian-9
      - Debian-Flavor
      - Linux
    memory: 512
    name: Debian-9-Stretch
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: bento/debian-10
    cpus: 1
    groups:
      - Debian
      - Debian-10
      - Debian-Flavor
      - Linux
    memory: 512
    name: Debian-10-Buster
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: bento/debian-11.1
    cpus: 1
    groups:
      - Debian
      - Debian-11
      - Debian-Flavor
      - Linux
    memory: 512
    name: Debian-11-Bullseye
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: alvistack/fedora-33
    cpus: 1
    groups:
      - Fedora
      - Fedora-33
      - Linux
      - RedHat-Flavor
    memory: 512
    name: Fedora-33
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: alvistack/fedora-34
    cpus: 1
    groups:
      - Fedora
      - Fedora-34
      - Linux
      - RedHat-Flavor
    memory: 512
    name: Fedora-34
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: alvistack/fedora-35
    cpus: 1
    groups:
      - Fedora
      - Fedora-35
      - Linux
      - RedHat-Flavor
    memory: 512
    name: Fedora-35
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: bento/ubuntu-18.04
    cpus: 1
    groups:
      - Debian-Flavor
      - Linux
      - Ubuntu
      - Ubuntu-18.04
    memory: 512
    name: Ubuntu-18.04-Bionic-Beaver
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: bento/ubuntu-20.04
    cpus: 1
    groups:
      - Debian-Flavor
      - Linux
      - Ubuntu
      - Ubuntu-20.04
    memory: 512
    name: Ubuntu-20.04-Focal-Fossa
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: bento/ubuntu-21.04
    cpus: 1
    groups:
      - Debian-Flavor
      - Linux
      - Ubuntu
      - Ubuntu-21.04
    memory: 512
    name: Ubuntu-21.04-Hirsute-Hippo
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: alvistack/ubuntu-21.10
    cpus: 1
    groups:
      - Debian-Flavor
      - Linux
      - Ubuntu
      - Ubuntu-21.10
    memory: 512
    name: Ubuntu-21.10-Impish-Indri
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: Megabyte/Windows-Desktop
    cpus: 2
    groups:
      - Windows
    memory: 4096
    name: Windows-10
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
      - "customize [ 'modifyvm', :id, '--natpf1', 'winrm,tcp,127.0.0.1,55985,,5985' ]"
provisioner:
  inventory:
    group_vars:
      Windows:
        ansible_become_method: runas
        ansible_connection: winrm
        ansible_winrm_scheme: http
        ansible_winrm_transport: basic
      all:
        ansible_become_password: ${TEST_USER:-vagrant}
        ansible_password: ${TEST_PASSWORD:-vagrant}
        ansible_user: ${TEST_USER:-vagrant}
    host_vars:
      Windows-10:
        ansible_host: 127.0.0.1
        ansible_port: 55985
