---
lsif:python:
  stage: lsif
  image: megabytelabs/lsif-python:latest
  allow_failure: true
  rules:
    - if: $DO_CI == 'false'
      when: never
    - if: $CI_COMMIT_BRANCH == 'synchronize'
      when: never
  needs: []
  script:
    - lsif-py .
  artifacts:
    reports:
      lsif: dump.lsif
