---
lsif:typescript:
  stage: lsif
  image: sourcegraph/lsif-node:latest
  allow_failure: true
  rules:
    - if: $DO_CI == 'false'
      when: never
    - if: $CI_COMMIT_BRANCH == 'synchronize'
      when: never
  needs: []
  script:
    - lsif-tsc -p .
  artifacts:
    reports:
      lsif: dump.lsif
