---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - box: Megabyte/Windows-Desktop
    cpus: 2
    groups:
      - windows
    memory: 4096
    name: Windows-10
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
      - "customize [ 'modifyvm', :id, '--natpf1', 'winrm,tcp,127.0.0.1,55985,,5985' ]"
provisioner:
  inventory:
    group_vars:
      all:
        virtualbox_molecule_test: true
      windows:
        ansible_become_method: runas
        ansible_become_user: vagrant
        ansible_password: vagrant
        ansible_user: vagrant
        ansible_winrm_scheme: http
        ansible_winrm_transport: basic
    host_vars:
      Windows-10:
        ansible_connection: winrm
        ansible_host: 127.0.0.1
        ansible_port: 55985
  name: ansible
  options:
    vvv: true
  playbooks:
    converge: converge.yml
    prepare: prepare.yml
scenario:
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  create_sequence:
    - dependency
    - create
    - prepare
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
