---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Bypass prepare stage
      debug:
        msg: Bypassing the prepare stage since the client is a Windows box
      changed_when: false
