---
version: '3'

tasks:
  benchmark:
    deps:
      - :install:npm:autocannon
      - :install:npm:clinic
    desc: Initiate a web server benchmarking session (with `clinic`)
    summary: |
      # Initiate a web server benchmarking session with `clinic`

      This task runs a basic stress test on an endpoint that is `/` by default.
      See the examples below for stress testing an endpoint other than the default.
      For more information, see the [`clinic` GitHub page](https://github.com/clinicjs/node-clinic).

      **Example usage:**
      `task npm:benchmark`

      **Example with custom endpoint:**
      `task npm:benchmark -- /custom/endpoint`
    cmds:
      - '{{.NPX_HANDLE}}clinic doctor --autocannon [ {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}/{{end}} --method POST ] -- node ./dist/main.js'
