---
description: Test using Docker containers (only Linux environments available)
driver:
  name: docker
groups:
  ArchLinux: Test on ArchLinux
  CentOS: Test on all CentOS containers
  CentOS-7: Test on CentOS 7
  CentOS-8: Test on CentOS 8
  Debian: Test on all Debian containers
  Debian-10: Test on Debian 10
  Debian-9: Test on Debian 9
  Debian-Flavor: Test on all Debian-flavored containers
  Fedora: Test on all Fedora containers
  Fedora-33: Test on Fedora 33
  Fedora-34: Test on Fedora 34
  RedHat-Flavor: Test on all RedHat-flavored containers
  Ubuntu: Test on all Ubuntu containers
  Ubuntu-18.04: Test on Ubuntu 18.04
  Ubuntu-20.04: Test on Ubuntu 20.04
  Ubuntu-21.04: Test on Ubuntu 21.04
platforms:
  - command: /sbin/init
    groups:
      - ArchLinux
      - Linux
    image: megabytelabs/ansible-molecule-archlinux:latest
    name: ArchLinux-Latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - command: /sbin/init
    groups:
      - CentOS
      - CentOS-7
      - Linux
      - RedHat-Flavor
    image: megabytelabs/ansible-molecule-centos-7:latest
    name: CentOS-7
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - command: /sbin/init
    groups:
      - CentOS
      - CentOS-8
      - Linux
      - RedHat-Flavor
    image: megabytelabs/ansible-molecule-centos-8:latest
    name: CentOS-8
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - command: /sbin/init
    groups:
      - Debian
      - Debian-9
      - Debian-Flavor
      - Linux
    image: megabytelabs/ansible-molecule-debian-9:latest
    name: Debian-9-Stretch
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - command: /sbin/init
    groups:
      - Debian
      - Debian-10
      - Debian-Flavor
      - Linux
      - Snap
    image: megabytelabs/ansible-molecule-debian-10:latest
    name: Debian-10-Buster
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - command: /sbin/init
    groups:
      - Fedora
      - Fedora-33
      - Linux
      - RedHat-Flavor
    image: megabytelabs/ansible-molecule-fedora-33:latest
    name: Fedora-33
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - command: /sbin/init
    groups:
      - Fedora
      - Fedora-34
      - Linux
      - RedHat-Flavor
    image: megabytelabs/ansible-molecule-fedora-34:latest
    name: Fedora-34
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - command: /sbin/init
    groups:
      - Debian-Flavor
      - Linux
      - Snap
      - Ubuntu
      - Ubuntu-18.04
    image: megabytelabs/ansible-molecule-ubuntu-18.04:latest
    name: Ubuntu-18.04-Bionic-Beaver
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - command: /sbin/init
    groups:
      - Debian-Flavor
      - Linux
      - Snap
      - Ubuntu
      - Ubuntu-20.04
    image: megabytelabs/ansible-molecule-ubuntu-20.04:latest
    name: Ubuntu-20.04-Focal-Fossa
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - command: /sbin/init
    groups:
      - Debian-Flavor
      - Linux
      - Snap
      - Ubuntu
      - Ubuntu-21.04
    image: megabytelabs/ansible-molecule-ubuntu-21.04:latest
    name: Ubuntu-21.04-Hirsute-Hippo
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  connection_options:
    ansible_connection: docker
    ansible_password: ${TEST_PASSWORD:-ansible}
    ansible_user: ${TEST_USER:-ansible}
  inventory:
    group_vars:
      all:
        ansible_become_password: ${TEST_BECOME_PASSWORD:-ansible}
        ansible_user: ${TEST_USER:-ansible}
