---
version: '3'

tasks:
  container-structure-test:
    deps:
      - container-structure-test:latest
      - container-structure-test:slim
    desc: Runs ContainerStructureTest for Dockerfile build

  container-structure-test:latest:
    deps:
      - :install:software:container-structure-test
    cmds:
      - |
        if [[ "$(docker images -q {{.DOCKERHUB_PROFILE}}/{{.SLUG}}:latest 2>/dev/null)" != "" ]]; then
          container-structure-test test --image {{.DOCKERHUB_PROFILE}}/{{.SLUG}}:latest --config test.yml
        fi

  container-structure-test:slim:
    deps:
      - :install:software:container-structure-test
    cmds:
      - |
        if [[ "$(docker images -q {{.DOCKERHUB_PROFILE}}/{{.SLUG}}:slim 2> /dev/null)" != "" ]]; then
          container-structure-test test --image {{.DOCKERHUB_PROFILE}}/{{.SLUG}}:slim --config test.yml
        fi
