---
version: '3'

tasks:
  container-structure-test:
    deps:
      - container-structure-test:latest
      - container-structure-test:slim
    desc: Runs ContainerStructureTest for Dockerfile build

  container-structure-test:latest:
    deps:
      - :install:software:container-structure-test
    cmds:
      - container-structure-test test --image {{.DOCKERHUB_PROFILE}}/{{.SLUG}}:latest --config test.yml
    log:
      error: '`container-structure-test` reported error(s) when testing `{{.DOCKERHUB_PROFILE}}/{{.SLUG}}:latest`'
      start: Testing the `{{.DOCKERHUB_PROFILE}}/{{.SLUG}}:latest` Docker image with `container-structure-test`
      success: '`{{.DOCKERHUB_PROFILE}}/{{.SLUG}}:latest` was successfully validated by `container-structure-test`'
    status:
      - '[[ "$(docker images -q {{.DOCKERHUB_PROFILE}}/{{.SLUG}}:latest 2>/dev/null)" == "" ]]'

  container-structure-test:slim:
    deps:
      - :install:software:container-structure-test
    cmds:
      - container-structure-test test --image {{.DOCKERHUB_PROFILE}}/{{.SLUG}}:slim --config test.yml
    log:
      error: '`container-structure-test` reported error(s) when testing `{{.DOCKERHUB_PROFILE}}/{{.SLUG}}:slim`'
      start: Testing the `{{.DOCKERHUB_PROFILE}}/{{.SLUG}}:slim` Docker image with `container-structure-test`
      success: '`{{.DOCKERHUB_PROFILE}}/{{.SLUG}}:slim` was successfully validated by `container-structure-test`'
    status:
      - '[[ "$(docker images -q {{.DOCKERHUB_PROFILE}}/{{.SLUG}}:slim 2> /dev/null)" == "" ]]'
