---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    role-file: requirements.yml
provisioner:
  name: ansible
  options:
    vvv: true
  playbooks:
    converge: ../converge.yml
    prepare: ../../.config/molecule/prepare.yml
verifier:
  name: ansible
