#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# @file .husky/commit-msg
# @brief A git hook script for the `commit-msg` hook

. "./.common/scripts/init.sh"

info "Validating commit message with 'commitlint'"
echo $1
echo "---"
echo $2
echo "----"
echo $3
task lint:commit -- "$2"
