#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# @file .husky/pre-commit
# @brief A git hook script for the `pre-commit` hook

. "./.common/scripts/init.sh"

info "Performing various pre-commit tasks on staged files (like autofixing, detecting private keys, etc.)"
STAGED_FILES=$(git diff --cached --name-only)
for FILE in "$STAGED_FILES"; do
  if [ -f "$1" ]; then
    task common:precommit -- "$FILE" &
  fi
done
wait

info "Linting and fixing the staged files with 'lint-staged'"
task lint:lint-staged

info "Reporting possible spelling errors in the staged files with 'cspell'"
task lint:spelling

success "pre-commit validation complete"
