#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

. "./.common/scripts/log.sh"

info "Checking for private keys in the repository"
detect-private-key **/*(^/)

info "Linting and fixing the staged files"
lint-staged

info "Reporting possible spelling errors in the staged files"
task spelling

success "Successfully validated the commit"
