---
name: macOS
"on":
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 2"

jobs:
  lint:
  integration:
    name: Integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-10.15

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Uninstall GitHub Actions' built-in Homebrew.
        run: |
          curl -sLO https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh
          chmod +x ./uninstall.sh
          sudo ./uninstall.sh --force
          sudo rm -rf /usr/local/Homebrew
          sudo rm -rf /usr/local/Caskroom
          sudo rm -rf /usr/local/bin/brew

      - name: Uninstall GitHub Actions' built-in browser installs.
        run: |
          sudo rm -rf /Applications/Firefox.app
          sudo rm -rf /Applications/Google\ Chrome.app

      - name: Install test dependencies.
        run: |
          sudo pip3 install ansible
          ansible-galaxy install -r requirements.yml

      - name: Set up the test environment.
        run: |
          cp tests/ansible.cfg ./ansible.cfg
          cp tests/inventory ./inventory
          cp tests/test.yml main.yml
          ROLE_FOLDER=$(basename "$PWD")
          sed -i "s/androidstudio/${ROLE_FOLDER}/g" main.yml

      - name: Test the playbook.
        env:
          ANSIBLE_FORCE_COLOR: "1"
        run: |
          ansible-playbook main.yml

      - name: Check for idempotence.
        env:
          ANSIBLE_FORCE_COLOR: "1"
        run: |
          idempotence=$(mktemp)
          ansible-playbook main.yml | tee -a ${idempotence}
          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
