language: node_js
node_js:
  - '10'
cache:
  bundler: true
  directories:
  - node_modules # NPM package
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f1d48355795bf25a8f9a
    on_success: change
    on_failure: always
    on_start: never
script: npm test
after_success: cat /home/travis/build/glayzzle/php-parser/coverage/lcov.info | /home/travis/build/glayzzle/php-parser/node_modules/coveralls/bin/coveralls.js
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
